apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: agent
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: agent
    spec:
      containers:
        - args:
            - agent
          env:
            - name: K3S_TOKEN
              value: secret
            - name: K3S_URL
              value: https://server:6443
          image: rancher/k3s:latest
          name: agent
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/rancher/k3s/registries.yaml
              name: agent-claim0
            - mountPath: /run
              name: agent-tmpfs0
            - mountPath: /var/run
              name: agent-tmpfs1
      restartPolicy: Always
      volumes:
        - name: agent-claim0
          persistentVolumeClaim:
            claimName: agent-claim0
        - emptyDir:
            medium: Memory
          name: agent-tmpfs0
        - emptyDir:
            medium: Memory
          name: agent-tmpfs1
status: {}
