apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "6443"
      port: 6443
      targetPort: 6443
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
