apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: server-claim1
  name: server-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
